### ISSUE TITLE
If internet connection is lost then the code freezes

### ISSUE THREAD

**Issue by niemilkm** [fopina/pyspeedtest#10]
Thank you for your code as it works very well.

I am doing some testing and after I do a ping using your code, I then do a download speed check. If I disconnect my internet between the ping and download speed check, the code freezes. Is there anyway to implement a timeout in your code to not allow it to freeze?

Thanks in advance!
Kevin

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
