### ISSUE TITLE
pyspeedtest.py crashing

### ISSUE THREAD

**Issue by pkilcoyne** [fopina/pyspeedtest#11]
To whom it concerns,
I love your code and it's functionality within python.

I'm running a python script where within a While True loop I call your download function, it runs for approx and hour or two and then crashes giving me the following error output;

- [ ] 1. Exception in thread Thread-1121:
- [ ] 2. Traceback (most recent call last):
- [ ] 3.   File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
- [ ] 4.     self.run()
- [ ] 5.   File "/usr/lib/python3.4/threading.py", line 868, in run
- [ ] 6.     self._target(*self._args, **self._kwargs)
- [ ] 7.   File "/usr/local/lib/python3.4/dist-packages/pyspeedtest.py", line 85, in downloadthread
- [ ] 8.     response = connection.getresponse()
- [ ] 9.   File "/usr/lib/python3.4/http/client.py", line 1172, in getresponse
- [ ] 10.     response.begin()
- [ ] 11.   File "/usr/lib/python3.4/http/client.py", line 351, in begin
- [ ] 12.     version, status, reason = self._read_status()
- [ ] 13.   File "/usr/lib/python3.4/http/client.py", line 321, in _read_status
- [ ] 14.     raise BadStatusLine(line)
- [ ] 15. http.client.BadStatusLine: ''
- [ ] 16. 
- [ ] 17. Traceback (most recent call last):
- [ ] 18.   File "speedtest.py", line 96, in <module>
- [ ] 19.     TestSpeed()
- [ ] 20.   File "speedtest.py", line 51, in TestSpeed
- [ ] 21.     down = round(st.download())
- [ ] 22.   File "/usr/local/lib/python3.4/dist-packages/pyspeedtest.py", line 107, in download
- [ ] 23.     **total_downloaded += thread.downloaded**
- [ ] 24. AttributeError: 'Thread' object has no attribute 'downloaded'

Is there a way to rectify this or is it somehow an issue with my script?

Many thanks,

Paul

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
