### ISSUE TITLE
Algorithm of chooseserver() does not handle exceptions

### ISSUE THREAD

**Issue by mkislik** [fopina/pyspeedtest#13]
When pyspeedtest.chooseserver() calls pyspeedtest.ping(), it does not catch exceptions, but should, since ping() does throw them.  Since the purpose of chooseserver() is to pick a server to run a speed-test against, a server that cannot be successfully connected to should be skipped.

    def chooseserver(self):
        ... (code is not relevant)
        for server in sorted_server_list[:10]:
            LOG.debug(server[1])
            match = re.search(
                r'http://([^/]+)/speedtest/upload\.php', server[1])
            if match is None:
                continue
            server_host = match.groups()[0]
            latency = self.ping(server_host)    <<-- statement needs try-except, with exception resulting in a call to "continue" for the loop
            if latency < best_server[0]:
                best_server = (latency, server_host)
        if not best_server[1]:
            raise Exception('Cannot find a test server')
        LOG.debug('Best server: %s', best_server[1])
        return best_server[1]

The stack trace I'm getting is when running on Windows 10 with pyspeedtest 1.2.7 is:
import pyspeedtest
st = pyspeedtest.SpeedTest(runs=1)
st.download()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyspeedtest.py", line 92, in download
    self.connect(self.host) for i in range(self.runs)
  File "C:\Python27\lib\site-packages\pyspeedtest.py", line 67, in host
    self._host = self.chooseserver()
  File "C:\Python27\lib\site-packages\pyspeedtest.py", line 230, in chooseserver
    latency = self.ping(server_host)
  File "C:\Python27\lib\site-packages\pyspeedtest.py", line 163, in ping
    connection = self.connect(server)
  File "C:\Python27\lib\site-packages\pyspeedtest.py", line 81, in connect
    raise Exception('Unable to connect to %r' % url)
Exception: Unable to connect to u'speedtest1.lpcnextlight.com'

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
