### ISSUE TITLE
chooseserver() fails when speedtest.net redirects to speedtest-servers-static.php

### ISSUE THREAD

**Issue by AJdeMooij** [fopina/pyspeedtest#14]
Lately speedtest.net responds to the GET request on `/speedtest-servers.php?` with a `307: moved temporarily` status code. The URL that should be requested is in the `location` header and (at the time of writing) becomes `/speedtest-servers-static.php` (although this may change in the future).

A request answered with status `307` has an empty response body, so the regular expression to find all servers listed in the response body results in an empty list. Consequently, no servers are tested, `best_servers` is a list with only one (the initial) item and `chooseserver()` raises the `"Cannot find a test server"` exception.

Various modules have intelligent request methods that automatically handle (temporary) redirects, but with the currently used `httplib` I cannot seem to find that option. The following code is a less clean but more simple solution:

1) Add import statements:
```python
try:
    from urlparse import urlparse
except ImportError:
    from urllib.parse import urlparse
```

2) Between https://github.com/fopina/pyspeedtest/blob/ba35921930dd7c9d864cbe08b5f76275e787af1f/pyspeedtest.py#L210 and https://github.com/fopina/pyspeedtest/blob/ba35921930dd7c9d864cbe08b5f76275e787af1f/pyspeedtest.py#L211 add the following:
```python
if(response.status >= 300 and response.status <= 400):
    u = urlparse(response.getheader('location'))
    redirected_connection = self.connect('c.speedtest.net')
    redirected_connection.request(
         'GET', u.path + '?x=%d' % now, None, extra_headers)
    response = redirected_connection.getresponse()
```

Now, if a redirect is issued by speedtest, a list of servers can still be retrieved. This is only a reference implementation to indicate the issue and suggest a solution. This code could be used, but is not a pull request.

As a note: I am not absolutely confident when speedtest.net will redirect to the static version of the servers page, but I assume this is related to some sort of rate limiting, where the list of nearby servers is not regenerated on every request.

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
