### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'rfind'

### ISSUE THREAD

**Issue by ishandutta2007** [fopina/pyspeedtest#20]
```
>>> import pyspeedtest
>>> st = pyspeedtest.SpeedTest()
>>> st.ping()
```

> Traceback (most recent call last):
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pyspeedtest.py", line 76, in connect
>     connection = HTTPConnection(url)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 849, in __init__
>     (self.host, self.port) = self._get_hostport(host, port)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/http/client.py", line 881, in _get_hostport
>     i = host.rfind(':')
> AttributeError: 'NoneType' object has no attribute 'rfind'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pyspeedtest.py", line 163, in ping
>     connection = self.connect(server)
>   File "/Users/ishandutta2007/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pyspeedtest.py", line 81, in connect
>     raise Exception('Unable to connect to %r' % url)
> Exception: Unable to connect to None
>

**Comment by bulbaasd** [comment]
Try this:
https://stackoverflow.com/questions/48289636/speedtest-python-script

**Comment by fopina** [comment]
https://github.com/fopina/pyspeedtest#discontinued :(
