### ISSUE TITLE
Not including ping in the output if user does not specify a server

### ISSUE THREAD

**Issue by sirgrigio** [fopina/pyspeedtest#5]
I was wondering why you decided to actually print the ping only if the user specify a server:

``` python
if opts.mode & 4 == 4 and opts.server is not None:
    print('Ping: %d ms' % speedtest.ping())
```

Wouldn't it be better to always include the ping in the output?

**Comment by fopina** [comment]
Indeed it seems I changed it on purpose to specifically print only when server is not chosen, but I can't remember why. I'll revert it until I remember why and make sure I leave a comment then!
